// Project > Properties > Change from Console Application to Windows Application when moving to production

namespace Source {
    internal class Program {
        static int Main(string[] args) {
            Task.Run(async void () => {
                GenesisStudio genesisStudio = new GenesisStudio();

                string[] urls = new string[] {
                    "https://genesistudio.com/viewer/2733",
"https://genesistudio.com/viewer/2734",
"https://genesistudio.com/viewer/2735",
"https://genesistudio.com/viewer/2736",
"https://genesistudio.com/viewer/2737",
"https://genesistudio.com/viewer/2738",
"https://genesistudio.com/viewer/2739",
"https://genesistudio.com/viewer/2740",
"https://genesistudio.com/viewer/2741",
"https://genesistudio.com/viewer/2742",
"https://genesistudio.com/viewer/2743",
"https://genesistudio.com/viewer/2744",
"https://genesistudio.com/viewer/2745",
"https://genesistudio.com/viewer/2746",
"https://genesistudio.com/viewer/2747",
"https://genesistudio.com/viewer/2748",
"https://genesistudio.com/viewer/2749",
"https://genesistudio.com/viewer/2750",
"https://genesistudio.com/viewer/2751",
"https://genesistudio.com/viewer/2752",
"https://genesistudio.com/viewer/2753",
"https://genesistudio.com/viewer/2754",
"https://genesistudio.com/viewer/2755",
"https://genesistudio.com/viewer/2756",
"https://genesistudio.com/viewer/2757",
"https://genesistudio.com/viewer/2758",
"https://genesistudio.com/viewer/2759",
"https://genesistudio.com/viewer/2760",
"https://genesistudio.com/viewer/2761",
"https://genesistudio.com/viewer/2762",
"https://genesistudio.com/viewer/2763",
"https://genesistudio.com/viewer/2764",
"https://genesistudio.com/viewer/2765",
"https://genesistudio.com/viewer/2766",
"https://genesistudio.com/viewer/2767",
"https://genesistudio.com/viewer/2768",
"https://genesistudio.com/viewer/2769",
"https://genesistudio.com/viewer/2770",
"https://genesistudio.com/viewer/2771",
"https://genesistudio.com/viewer/2772",
"https://genesistudio.com/viewer/2773",
"https://genesistudio.com/viewer/2774",
"https://genesistudio.com/viewer/2775",
"https://genesistudio.com/viewer/2776",
"https://genesistudio.com/viewer/2777",
"https://genesistudio.com/viewer/2778",
"https://genesistudio.com/viewer/2779",
"https://genesistudio.com/viewer/2780",
"https://genesistudio.com/viewer/2781",
"https://genesistudio.com/viewer/2782",
"https://genesistudio.com/viewer/2783",
"https://genesistudio.com/viewer/2784",
"https://genesistudio.com/viewer/2785",
"https://genesistudio.com/viewer/2786",
"https://genesistudio.com/viewer/2787",
"https://genesistudio.com/viewer/2788",
"https://genesistudio.com/viewer/2789",
"https://genesistudio.com/viewer/2790",
"https://genesistudio.com/viewer/2791",
"https://genesistudio.com/viewer/2792",
"https://genesistudio.com/viewer/2793",
"https://genesistudio.com/viewer/2794",
"https://genesistudio.com/viewer/2795",
"https://genesistudio.com/viewer/2796",
"https://genesistudio.com/viewer/2797",
"https://genesistudio.com/viewer/2798",
"https://genesistudio.com/viewer/2799",
"https://genesistudio.com/viewer/2800",
"https://genesistudio.com/viewer/2801",
"https://genesistudio.com/viewer/2802",
"https://genesistudio.com/viewer/2803",
"https://genesistudio.com/viewer/2804",
"https://genesistudio.com/viewer/2805",
"https://genesistudio.com/viewer/2806",
"https://genesistudio.com/viewer/2807",
"https://genesistudio.com/viewer/2808",
"https://genesistudio.com/viewer/2809",
"https://genesistudio.com/viewer/2810",
"https://genesistudio.com/viewer/2811",
"https://genesistudio.com/viewer/2812",
"https://genesistudio.com/viewer/2813",
"https://genesistudio.com/viewer/2814",
"https://genesistudio.com/viewer/2815",
"https://genesistudio.com/viewer/2816",
"https://genesistudio.com/viewer/2817",
"https://genesistudio.com/viewer/2818",
"https://genesistudio.com/viewer/2819",
"https://genesistudio.com/viewer/2820",
"https://genesistudio.com/viewer/2821",
"https://genesistudio.com/viewer/2822",
"https://genesistudio.com/viewer/2823",
"https://genesistudio.com/viewer/2824",
"https://genesistudio.com/viewer/2825",
"https://genesistudio.com/viewer/2826",
"https://genesistudio.com/viewer/2827",
"https://genesistudio.com/viewer/2828",
"https://genesistudio.com/viewer/2829",
"https://genesistudio.com/viewer/2830",
"https://genesistudio.com/viewer/2831",
"https://genesistudio.com/viewer/2832",
"https://genesistudio.com/viewer/2833",
"https://genesistudio.com/viewer/2834",
"https://genesistudio.com/viewer/2835",
"https://genesistudio.com/viewer/2836",
"https://genesistudio.com/viewer/2837",
"https://genesistudio.com/viewer/2838",
"https://genesistudio.com/viewer/2839",
"https://genesistudio.com/viewer/2840",
"https://genesistudio.com/viewer/2841",
"https://genesistudio.com/viewer/2842",
"https://genesistudio.com/viewer/2843",
"https://genesistudio.com/viewer/2844",
"https://genesistudio.com/viewer/2845",
"https://genesistudio.com/viewer/2846",
"https://genesistudio.com/viewer/2847",
"https://genesistudio.com/viewer/2848",
"https://genesistudio.com/viewer/2849",
"https://genesistudio.com/viewer/2850",
"https://genesistudio.com/viewer/2851",
"https://genesistudio.com/viewer/2852",
"https://genesistudio.com/viewer/2853",
"https://genesistudio.com/viewer/2854",
"https://genesistudio.com/viewer/2855",
"https://genesistudio.com/viewer/2856",
"https://genesistudio.com/viewer/2857",
"https://genesistudio.com/viewer/2858",
"https://genesistudio.com/viewer/2859",
"https://genesistudio.com/viewer/2860",
"https://genesistudio.com/viewer/2861",
"https://genesistudio.com/viewer/2862",
"https://genesistudio.com/viewer/2863",
"https://genesistudio.com/viewer/2864",
"https://genesistudio.com/viewer/2865",
"https://genesistudio.com/viewer/2866",
"https://genesistudio.com/viewer/2867",
"https://genesistudio.com/viewer/2868",
"https://genesistudio.com/viewer/2869",
"https://genesistudio.com/viewer/2870",
"https://genesistudio.com/viewer/5288",
"https://genesistudio.com/viewer/5289",
"https://genesistudio.com/viewer/5290",
"https://genesistudio.com/viewer/5291",
"https://genesistudio.com/viewer/5292",
"https://genesistudio.com/viewer/5293",
"https://genesistudio.com/viewer/5294",
"https://genesistudio.com/viewer/5295",
"https://genesistudio.com/viewer/5296",
"https://genesistudio.com/viewer/5297",
"https://genesistudio.com/viewer/5298",
"https://genesistudio.com/viewer/5299",
"https://genesistudio.com/viewer/5367",
"https://genesistudio.com/viewer/5403",
"https://genesistudio.com/viewer/5422",
"https://genesistudio.com/viewer/5492",
"https://genesistudio.com/viewer/5622",
"https://genesistudio.com/viewer/5841",
"https://genesistudio.com/viewer/5858",
"https://genesistudio.com/viewer/5898",
"https://genesistudio.com/viewer/6016",
"https://genesistudio.com/viewer/6037",
"https://genesistudio.com/viewer/6059",
"https://genesistudio.com/viewer/6060",
"https://genesistudio.com/viewer/6153",
"https://genesistudio.com/viewer/6170",
"https://genesistudio.com/viewer/6190",
"https://genesistudio.com/viewer/6208",
"https://genesistudio.com/viewer/6320",
"https://genesistudio.com/viewer/6349",
"https://genesistudio.com/viewer/6375",
"https://genesistudio.com/viewer/6376",
"https://genesistudio.com/viewer/6479",
"https://genesistudio.com/viewer/6512",
"https://genesistudio.com/viewer/6518",
"https://genesistudio.com/viewer/6548",
"https://genesistudio.com/viewer/6611",
"https://genesistudio.com/viewer/6622",
"https://genesistudio.com/viewer/6629",
"https://genesistudio.com/viewer/6653",
"https://genesistudio.com/viewer/6725",
"https://genesistudio.com/viewer/6745",
"https://genesistudio.com/viewer/6751",
"https://genesistudio.com/viewer/6760",
"https://genesistudio.com/viewer/6813",
"https://genesistudio.com/viewer/6818",
"https://genesistudio.com/viewer/6822",
"https://genesistudio.com/viewer/6856",
"https://genesistudio.com/viewer/6864",
"https://genesistudio.com/viewer/6869",
"https://genesistudio.com/viewer/6873",
"https://genesistudio.com/viewer/6879",
"https://genesistudio.com/viewer/6888",
"https://genesistudio.com/viewer/6972",
"https://genesistudio.com/viewer/6974",
"https://genesistudio.com/viewer/6985",
"https://genesistudio.com/viewer/7002",
"https://genesistudio.com/viewer/7003",
"https://genesistudio.com/viewer/7008",
"https://genesistudio.com/viewer/7015",
"https://genesistudio.com/viewer/7023",
"https://genesistudio.com/viewer/7024",
"https://genesistudio.com/viewer/7032",
"https://genesistudio.com/viewer/7038",
"https://genesistudio.com/viewer/7045",
"https://genesistudio.com/viewer/7080",
"https://genesistudio.com/viewer/7106",
"https://genesistudio.com/viewer/7174",
"https://genesistudio.com/viewer/7184",
"https://genesistudio.com/viewer/7185",
"https://genesistudio.com/viewer/7235",
                };

                const int chapterPerVolume = 100;

                int volume = 1;
                int chapter = 1;
                foreach (string url in urls) {
                    Console.WriteLine($"{url}");
                    await genesisStudio.DownloadChapter(url, @"D:\Visual Novels\[Self-Sourced] [Ongoing] Becoming Professor Probability\Raw\" + $"Volume {volume}", $"{(chapter++).ToString("D4")}.xhtml");

                    if (chapter > chapterPerVolume) {
                        ++volume;
                        chapter = 1;
                    }

                    Thread.Sleep(1500); // Cloudflare rate limiting
                }

                Console.WriteLine("Done!");
            });

            Console.ReadLine();

            return 0;
        }
    }
}