// Project > Properties > Change from Console Application to Windows Application when moving to production

namespace Source {
    internal class Program {
        static int Main(string[] args) {
            Task.Run(async void () => {
                YukiKitsuneko yuki = new YukiKitsuneko();

                /*string[] urls = {
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-illustrations.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c1.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c2.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c3.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c4.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c5.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c6.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c7.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c8.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c9.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-c10.html",
"https://yukikitsuneko.blogspot.com/2025/04/arrogant-queen-v1-afterword.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-illustrations.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c1.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c2.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c3.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c4.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c5.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c6.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c7.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c8.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c9.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-c10.html",
"https://yukikitsuneko.blogspot.com/2025/05/arrogant-queen-v2-afterword.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-illustrations.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c1.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c2.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c3.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c4.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c5.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c6.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c7.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c8.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c9.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-c10.html",
"https://yukikitsuneko.blogspot.com/2025/06/arrogant-queen-v3-afterword.html",
"https://yukikitsuneko.blogspot.com/2025/11/arrogant-queen-v4-illustrations.html",
"https://yukikitsuneko.blogspot.com/2025/11/arrogant-queen-v4-c1.html",
"https://yukikitsuneko.blogspot.com/2025/11/arrogant-queen-v4-c2.html",
"https://yukikitsuneko.blogspot.com/2025/11/arrogant-queen-v4-c3.html",
"https://yukikitsuneko.blogspot.com/2025/11/arrogant-queen-v4-c4.html",
"https://yukikitsuneko.blogspot.com/2025/11/arrogant-queen-v4-c5.html",
                };*/

                string[] urls = {
                "https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e1.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e2.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e3.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e4.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e5.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e6.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e7.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e8.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e9.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e10.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e11.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e12.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e13.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e14.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e15.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e16.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e17.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e18.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e19.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e20.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e21.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e22.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e23.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e24.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e25.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e26.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e27.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e28.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e29.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e30.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e31.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e32.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e33.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e34.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e35.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e36.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e37.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e38.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e39.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e40.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e41.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e42.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e43.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e44.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e45.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e46.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e47.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e48.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e49.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e50.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e51.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e52.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e53.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e54.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e55.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e56.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e57.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e58.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e59.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e60.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e61.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e62.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e63.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e64.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e65.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e66.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e67.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e68.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e69.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e70.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e71.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e72.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e73.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e74.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e75.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e76.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e77.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e78.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e79.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e80.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e81.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e82.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e83.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e84.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e85.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e86.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e87.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e88.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e89.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e90.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e91.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e92.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e93.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e94.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e95.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e96.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e97.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e98.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e99.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e100.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e101.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e102.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e103.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e104.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e105.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e106.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e107.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e108.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e109.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e110.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e111.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e112.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e113.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e114.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e115.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e116.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e117.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e118.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e119.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e120.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e121.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e122.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e123.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e124.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e125.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e126.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e127.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e128.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e129.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e130.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e131.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e132.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e133.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e134.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e135.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e136.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e137.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e138.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e139.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e140.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e141.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e142.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e143.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e144.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e145.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e146.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e147.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e148.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e149.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e150.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e151.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e152.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e153.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e154.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e155.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e156.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e157.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e158.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e159.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e160.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e161.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e162.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e163.html",
"https://yukikitsuneko.blogspot.com/2025/10/having-meals-with-my-beautiful-coworker-e164.html",
                };

                const int chapterPerVolume = 100;

                int skip = 0;

                int volume = 1;
                int chapter = 1;
                for (int i = 0; i < urls.Length; ++i) {
                    var url = urls[i];

                    Console.WriteLine($"{url}");

                    if (i >= skip) {
                        await yuki.DownloadChapter(url, @"D:\Visual Novels\[Self-Sourced] [Web Novel] My daily life having meals with my beautiful coworker from sales\Raw\" + $"Volume {volume}", $"{chapter.ToString("D4")}.xhtml");
                    }

                    if ((++chapter) > chapterPerVolume) {
                        ++volume;
                        chapter = 1;
                    }

                    if (i >= skip) {
                        Thread.Sleep(1000); // Cloudflare rate limiting
                    }
                }

                Console.WriteLine("Done!");
            });

            Console.ReadLine();

            return 0;
        }
    }
}